server:
  port: 8080
spring:
  application:
    name: XingChen
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/starstudio?serverTimezone=UTC&useSSL=false
    username: root
    password: abc123
  redis:
    host: 192.168.1.150
    port: 6379
    password: 250237
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  configuration:
    #??????????????????????????????????????? ?address_book -->AddressBook
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
liaohui:
   path: D:/images/